# Generated by Django 5.0.6 on 2024-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(null=True, upload_to='recipie_image'),
        ),
    ]
